# Model Parameters
model:
  type: matrix_factorization       
  embedding_dim: 50               
  learning_rate: 0.01           
  regularization: 0.1              
  num_epochs: 100               
  batch_size: 64                  

# Candidate Generation Parameters
candidate_generation:
  top_k: 100                       
  exclude_seen_items: true         
  popularity_filter:              
    min_interactions: 10           
  diversity:
    enabled: true                 
    max_similar_items: 3          

# Data Parameters
data:
  user_data_path: data/raw/users.csv     
  item_data_path: data/raw/items.csv     
  interaction_data_path: data/raw/interactions.csv  

# Embeddings
embeddings:
  save_path: data/embeddings/           
  load_existing: false                   

# Evaluation Parameters
evaluation:
  validation_split: 0.2                  
  metrics:                               
    - precision_at_k
    - recall_at_k
    - ndcg
